---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "hmappteam6"
  namespace: "default"
  labels:
    app: "hmappteam6"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "hmappteam6"
  template:
    metadata:
      labels:
        app: "hmappteam6"
    spec:
      containers:
      - name: "database-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/farin77/database@sha256:5a281b8aaf93932b59355fe7b16636a464dd648fc2d5738e60e352612e891e4a"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "hmappteam6-hpa-ks0p"
  namespace: "default"
  labels:
    app: "hmappteam6"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "hmappteam6"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
