---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "hmapp9"
  namespace: "default"
  labels:
    app: "hmapp9"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "hmapp9"
  template:
    metadata:
      labels:
        app: "hmapp9"
    spec:
      containers:
      - name: "database-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/farin77/database@sha256:ae5bb3ea9ce7ec3824eb522686c49919db38a682287833fc3df79ad55f1848a1"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "hmapp9-hpa-dkau"
  namespace: "default"
  labels:
    app: "hmapp9"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "hmapp9"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
